name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: 3tTGDjvzt6Cf7rf5uqHypvoVl58KhTOK:61d5b416556524b504cd23c6
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: '../../worklist.yaml'
          # api-version: 'v1.0.0'
